CREATE TABLE campus_resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    resource_type VARCHAR(24) NOT NULL,
    location VARCHAR(160) NOT NULL,
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT NOT NULL REFERENCES campus_resource(id),
    booked_by VARCHAR(160) NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    purpose VARCHAR(240) NOT NULL,
    status VARCHAR(24) NOT NULL,
    check_in_code VARCHAR(16) NOT NULL UNIQUE,
    checked_in_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT booking_time_range CHECK (end_time > start_time)
);

CREATE INDEX idx_booking_resource_time
    ON booking(resource_id, start_time, end_time);

CREATE INDEX idx_booking_owner
    ON booking(booked_by);
