CREATE TABLE student_workspace (
    owner_email VARCHAR(160) PRIMARY KEY
);

CREATE TABLE study_subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_email VARCHAR(160) NOT NULL REFERENCES student_workspace(owner_email),
    code VARCHAR(24) NOT NULL,
    name VARCHAR(120) NOT NULL,
    semester VARCHAR(80) NOT NULL,
    color VARCHAR(7) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_subject_owner_code UNIQUE (owner_email, code)
);

CREATE TABLE degree_goal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL REFERENCES study_subject(id),
    owner_email VARCHAR(160) NOT NULL REFERENCES student_workspace(owner_email),
    title VARCHAR(160) NOT NULL,
    goal_type VARCHAR(32) NOT NULL,
    priority VARCHAR(16) NOT NULL,
    planned_start TIMESTAMP WITH TIME ZONE,
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    notes VARCHAR(1000) NOT NULL,
    evidence_url VARCHAR(500),
    portfolio_visible BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(24) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT goal_time_range CHECK (planned_start IS NULL OR due_at > planned_start)
);

CREATE INDEX idx_goal_owner_due ON degree_goal(owner_email, due_at);
CREATE INDEX idx_goal_owner_status ON degree_goal(owner_email, status);
CREATE INDEX idx_goal_subject ON degree_goal(subject_id);
CREATE INDEX idx_goal_portfolio ON degree_goal(portfolio_visible, status);
